// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaQjqpEPX66E9R8ims6maYDzdJeilUrnw',
    appId: '1:302971606047:web:626a73ec0940585c8ef12a',
    messagingSenderId: '302971606047',
    projectId: 'rightchat-4306d',
    authDomain: 'rightchat-4306d.firebaseapp.com',
    storageBucket: 'rightchat-4306d.appspot.com',
    measurementId: 'G-8EE32CZLGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvas7dFuEqx5xQ1PNp0xVsgDEjTyCB7jE',
    appId: '1:302971606047:android:ac0f64156a8bccfb8ef12a',
    messagingSenderId: '302971606047',
    projectId: 'rightchat-4306d',
    storageBucket: 'rightchat-4306d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgKbAnteZxwnu8-wCvuv-92hjTGYzWBrI',
    appId: '1:302971606047:ios:35d419ec4c7886908ef12a',
    messagingSenderId: '302971606047',
    projectId: 'rightchat-4306d',
    storageBucket: 'rightchat-4306d.appspot.com',
    iosBundleId: 'com.example.rightchatApp',
  );
}
